### ISSUE TITLE
Split names_and_entities.pig into two scripts

### ISSUE THREAD

**Issue by jodaiber** [dbpedia-spotlight/pignlproc#3]
Because we are writing out the surface forms, which are put into the distributed cache to collect ngrams, names_and_entities.pig has to either use EXEC or -no_multiquery. No multiquery exectution makes the script slower. The script should be split into two scripts: 1. collect and store surface forms 2. perform the rest of the tasks.

**Comment by maxjakob** [comment]
Just curious if you also tried a [replicated join](http://pig.apache.org/docs/r0.10.0/perf.html#replicated-joins) that loads one bag into memory and streams the other one through?
Should be sort of equivalent to [using the RestrictedNGramGenerator UDF](https://github.com/dbpedia-spotlight/pignlproc/blob/f10158f99df5c414cf242c8e1ed617f6c2cc0152/examples/indexing/names_and_entities.pig#L121).

**Comment by jodaiber** [comment]
This is not necessary anymore, as it works rather well with the EXEC version.
