### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by maxjakob** [dbpedia-spotlight/pignlproc#4]
[Scala](http://en.wikipedia.org/wiki/Scala_%28programming_language%29) is for sure refered to more often than 3 times and at least once [with the string "Scala"](http://en.wikipedia.org/wiki/Exception_handling#Exception_support_in_programming_languages).

However, everything that shows up for it after running nerd-stats.pig is

```
Scala (programming language)    Scala programming language  0.42857142857142855 1.0 0.6363636363636364  3254510 3
```

This likely also affects the scripts that calculate the absolute counts.

**Comment by jodaiber** [comment]
In the English version?

sf:

```
 Scala  228 4117
```

pairs:

```
Scala   http://en.wikipedia.org/wiki/Scala_(programming_language)   133
Scala programming language  http://en.wikipedia.org/wiki/Scala_(programming_language)   4
Scala programming language  http://en.wikipedia.org/wiki/Scala_%28programming_language%29   3
```

**Comment by maxjakob** [comment]
This was related to `examples/nerd-stats/nerd-stats.pig` only.

_Caution:_ The `pageUrl`s that fall out of the `ParsingWikipediaLoader` are not compatible with the `targetUri`s from `SentencesWithLink` because the former are %-encoded and the latter are (usually) not because it is taken straight from the wiki link.
I am going to fix this for this script.
