### ISSUE TITLE
Deduplicate using macros

### ISSUE THREAD

**Issue by maxjakob** [dbpedia-spotlight/pignlproc#5]
There is a lot of duplicated code in the Pig Latin scripts, for example redirect resolution in
- [names_and_entities.pig](https://github.com/dbpedia-spotlight/pignlproc/blob/master/examples/indexing/names_and_entities.pig#L48)
- [sf_uri_group.pig](https://github.com/dbpedia-spotlight/pignlproc/blob/master/examples/indexing/sf_uri_group.pig#L30)

[Macros](http://pig.apache.org/docs/r0.10.0/cont.html#define-macros) can be used to de-duplicate and make the scripts more readable.

**Comment by jodaiber** [comment]
Is sf_uri_group.pig actually used anywhere? 
/cc @chrishokamp

**Comment by jodaiber** [comment]
Aditionally, there is now names_and_entities_low_memory.pig, which is the same as names_and_entities.pig but does not load SFs into memory. If anybody with more Pig experience can refactor those two scripts, it would be great!

**Comment by maxjakob** [comment]
For the record: nerd.stats.pig  does normalization of the counts produced in  names_and_entities[_low_memory].pig, so this can also be refactored.
